const stages = [
    {
        name:'stage 1',
        images:{
            background:'assets/stages/stage1/bg1.jpg',
            floor:'assets/stages/stage1/ground.jpg'
        },
        width:1920,
        height:1080,
        patterns:[
            {
                cycles:0,
                randomized:false,
                data:[
                    [0,0,0,0,0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0,0,0,0,0],
                    [1,1,1,1,1,1,1,1,1,1,1,1,1],
                ]
            },
            {
                cycles:1,
                randomized:false,
                data:[
                    [0,0,0,0,0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,1,0,0,0,0,1,0,0,0],
                    [1,1,1,1,1,1,1,1,1,1,1,1,1],
                ]
            },
            {
                cycles:1,
                randomized:false,
                data:[
                    [0,0,0,0,0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,1,1,0,0,0,0,0],
                    [1,1,1,1,1,1,1,1,1,1,1,1,1],
                ]
            },
            
        ]
    },
    {
        name:'stage 2',
        images:{
            background:'assets/stages/stage1/bg1.jpg',
            floor:'assets/stages/stage1/ground.jpg'
        },
        width:1920,
        height:1080,
        patterns:[
            {
                cycles:0,
                randomized:false,
                data:[
                    [0,0,0,0,0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0,0,0,0,0],
                    [1,1,1,1,1,1,1,1,1,1,1,1,1],
                ]
            },
            {
                cycles:5,
                randomized:true,
                data:[
                    [0,0,0,0,1,0,0,0,0,1,0,0,0],
                    [0,0,1,0,0,1,0,0,1,0,0,0,0],
                    [1,1,1,1,1,1,1,1,1,1,1,1,0],
                ]
            }
        ]
    },
    {
        name:'stage 3',
        images:{
            background:'assets/stages/stage1/bg1.jpg',
            floor:'assets/stages/stage1/ground.jpg'
        },
        width:1920,
        height:1080,
        patterns:[
            {
                cycles:5,
                randomized:true,
                data:[
                    [0,1,0,0,0,0,1,0,0,1,0,0,0],
                    [0,0,0,0,1,0,0,0,1,0,0,0,0],
                    [1,1,0,1,1,1,0,1,1,0,1,1,1],
                ]
            },
            {
                cycles:5,
                randomized:false,
                data:[
                    [0,0,1,1,1,0,0,1,0,1,0,0,0],
                    [0,0,1,0,0,0,1,0,1,0,0,0,0],
                    [1,1,0,0,1,0,1,0,1,0,0,1,1],
                ]
            }
        ]
    }
]

const characters = [
    {
        name:'sakura',
        image_path:'assets/characters/char1/',
        special:'pogostick',
        state_animation_frames:{
            idle:1,
            running:6,
            jumping:5,
            mid_air:1,
            falling:5
        }
    },
    {
        name:'sakura 2',
        image_path:'assets/characters/char1/',
        special:'flowstate',
        state_animation_frames:{
            idle:1,
            running:6,
            jumping:5,
            mid_air:1,
            falling:5
        }
    },
    {
        name:'jackie',
        image_path:'assets/characters/jackie/',
        special:'flowstate',
        state_animation_frames:{
            idle:2,
            running:2,
            jumping:2,
            mid_air:2,
            falling:2
        }
    },
    {
        name:'mai',
        image_path:'assets/characters/mai/',
        special:'rope',
        state_animation_frames:{
            idle:1,
            running:6,
            jumping:3,
            mid_air:1,
            falling:4
        }
    },
    {
        name:'felicia',
        image_path:'assets/characters/felicia/',
        special:'phantom dash',
        state_animation_frames:{
            idle:1,
            running:6,
            jumping:3,
            mid_air:1,
            falling:3
        }
    }
]